language: node_js
node_js:
  - '6'
script: npm test
deploy:
  provider: npm
  email: jmsmyth@users.noreply.github.com
  api_key:
    secure: boIMB12K5HPWP237qCbhb7+3nY86isKfmSDb2IiNauJbXGPox7X4KmhzsFNAE56jqX9GSfb2LnmXQujKNPLbXBAL1rTNTIKO90uFW1uLWXNICYi81fdhtaw8ZUW8qxRNZAD0so6KJCxNWCy92AR5S4B+nmPxc+ZQSd43EIdTSpLkR80v9cxk0D9JtRVdd6XhjbFFLT+1U6p/UG+VviN8ajnYAQ1+Hb5cp80WmV+nzRTXWtcg0cXqjSFeDtqioKhXd8ywjmOjvgY0N2BthwUINpNJ24hSNKRi74DSG97Yihd2QzV/A0zpRMHPKuRniIDKV824N13093Xa/pjcI4KOu5/m69Vt3BiG3JhihpMv3qdfiUpEidaf/8qQZq81EZcdiUpzSpDDjSChXdwXnpfZcoqwIWGRIVDq2XylnoJg4zwBeAqoCXL+WS8hICacR9iDRVbEwhmwo0/i9B1kvLLJxulfaBXby6Sn1qezULfaaNcFh7gWyzIkuWmA0I5gl+FAe8c3eafQe9SZpBeuWlZ0q1+cBC2fXQc+PawbOjvqMj10+PKFUcLJtxLF+4F+izKAtjPj+n9MvxZLyK/e2q7E2pE+m3+P83gJszULEGiqH+1BerTfKn5sbySQylPZ7Ejn3RKj5EA+ZAIfAy4PVf9cxG8qHyjar4SvEEBQdZ78Tyw=
  on:
    tags: true
    repo: jmsmyth/hexagon-rx
