language: node_js
node_js:
  - '6'
script: npm test
deploy:
  provider: npm
  email: jmsmyth@users.noreply.github.com
  api_key:
    secure: jLvR3LTOmj2U3kT+pDwPB2G5PMn/be50QWiRlOmRHy2n2ZpcjMiEpGrtLgcLrv6z9V6CUJLql9rfwAaqokh7gCc8xDubE20cJAaTj3fgee3RegMP3SiZX5Gbk+17n1GJQWrvj2ue55sc2zjZDSffm17Ou58/jPvadSeTOty/8cXXnUD/yqtkzWrkVPraIaLSqGkrHS2pJPnq4Mibwzz/gDDD6sd9DAVR1z+lQ/5wyibWkam98CsrPBh+YwaeOVk3+HCqAqGz6C3DOCcfpZ5rxwwxUtdzp57+nqtL7e4U0fR3LZxs8pWQ9VJ8YpfX013I+5dKY2FRhugobg/lw7WXlGCaVSd6AUdJtCpgqFy2JfL+bL9U13kmgw5MYmKA08/4L+qBQ8j+Nl/VMXFDdReyVvNPr3TCn5beCYN4SZenxJ07hCXZV0SXn6EaUfn31w9LuLVRtodqFhsJXfH0pdivaSANdh+o+lQlZz7J6jbBhcrapXbfO2WBwj1LFAdRVwm6vTk09BTl+teTDiAYGhn0SBTzEXBPLCp5lddhxgkvYn1mgv8bmUVESuXE0pOMoA+q+08ezFrVXUMPTeCTpO2VPzYUr7Dd+y723VNHEw1DLIVUxyDBpxu2BDQCJBmLJ/KjijB26YJ1DBD+Udd0rDVWA60z/hHfzmanpXs00TxU4zo=
  on:
    tags: true
    repo: jmsmyth/hexagon-rx
